version: '3.8'

networks:
  my_network:
    name: my_network

volumes:
  mysql_data:
    name: mysql_data

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dainius_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    networks:
      - my_network

  liquibase:
    image: liquibase/liquibase:4.21.1
    environment:
      INSTALL_MYSQL: true
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command: update --url=jdbc:mysql://mysql:3306/dainius_db?user=root'&'password=1234 --changelog-file=changelog/db.changelog-master.yaml
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "liquibase --url=jdbc:mysql://mysql:3306/dainius_db?user=root'&'password=1234 --changelog-file=changelog/db.changelog-master.yaml --logLevel=debug --diff" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    networks:
      - my_network


  dainius-service:
    image: dainius-stocks-pricing-service:latest
    ports:
      - "8080:9090"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dainius_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - my_network
    restart: on-failure
