spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dainius_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver  # Use the driver class name for the chosen MySQL connector version

  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.yaml
    parameters:
      driver: com.mysql.cj.jdbc.Driver  # Make sure it matches the driver class name above
    enabled: false


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            jdbc: DEBUG
