spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dainius_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  parameters:
    driver: com.mysql.cj.jdbc.Driver
  enabled: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            jdbc: DEBUG

server:
  port: 9090
