spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dainius_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: false

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            jdbc: DEBUG

server:
  port: 9090
