spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dainius_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            jdbc: DEBUG
